from typing import NamedTuple


class GDALDataFinder:
    ...

class GDALVersion(NamedTuple):
    major: int
    minor: int
    revision: int

class PROJDataFinder:
    ...

def calc_gdal_version_num(maj: int, min: int, rev: int) -> int: ...

def get_gdal_release_name() -> str: ...

def get_gdal_version_num() -> int: ...

def get_gdal_version_tuple() -> GDALVersion: ...

def get_proj_version_tuple() -> tuple[int, int, int]: ...